choco install microsoft-teams -y
choco install whatsapp -y
choco install slack -y
choco install openhardwaremonitor -y
choco install vlc -y
choco install f.lux -y
choco install cpu-z -y
choco install hyper -y
choco install conemu -y
choco install mobaxterm -y
choco install vscode -y
choco install steam -y
choco install virtualbox -y
choco install git -y
choco install geforce-experience -y
choco install autohotkey -y
choco install discord -y